spring.application.name=medicenter

spring.datasource.url=jdbc:mysql://localhost:3306/medicenter_db?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

medicenter.admin.senha=${ADMIN_SENHA:admin123}